name: Offset Industries
favicon: null
layout_spectrum: 0.49731
typography_spectrum: 0.24564
title: Our Vision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9b9b9b'
    - '#4f276d'
    - '#525252'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.33813053532503545
purpose: []
